version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        url: https://github.com/alexey0101/PasswordGenerator.git
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=master